########################################################################################
# GCC template makefile
########################################################################################

MENU_SRCS = led_menu.c
MENU_SRCS += key_menu.c
MENU_SRCS += seg_menu.c
MENU_SRCS += main_menu.c


SRCS += $(MENU_SRCS)

